env: prod
mcp:
  name: example-servers/everything
  version: 1.0.0
  sse_addr: :3001
  http_addr: :3002
data:
  db:
    user:
      driver: sqlite
      dsn: storage/nunu-test.db?_busy_timeout=5000
  #    user:
  #      driver: mysql
  #      dsn: root:123456@tcp(127.0.0.1:3380)/user?charset=utf8mb4&parseTime=True&loc=Local
  #    user:
  #      driver: postgres
  #      dsn: host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable TimeZone=Asia/Shanghai
  redis:
    addr: 127.0.0.1:6350
    password: ""
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s

log:
  log_level: info
  mode: file               #  file or console or both
  encoding: json           # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true